import "@/styles/globals.css";
import { SWRConfig } from 'swr'
import fetchJson from '@/lib/fetchJson'
import Head from 'next/head'
import { Layout } from "@/modules/layout";

export default function App({ Component, pageProps }) {
  return (
    <SWRConfig
      value={{
        fetcher: fetchJson,
        onError: (err) => {
          console.error(err)
        },
      }}
    >
      <Head>
        <title>Social Money</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
      </SWRConfig>
  );
}