import Head from "next/head";
import { Poppins } from "next/font/google";

import { Navbar } from "./Navbar";
import { BottomNav } from "./BottomNav";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Social Money</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`${poppins.className} h-screen flex items-center justify-center`}>
        <Navbar />

        <main className="w-full mt-[16px]">
          {children}
        </main>

        <BottomNav/>
      </div>
    </>
  );
};

export { Layout };
